name: 2fa-express
on:
    push:
        branches:
            - main
    pull_request:

env:
  VERSION: v1.0

jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Log into registry
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Build image
              run: |
                  touch .env
                  cat $ENV > .env
                  docker build -t 2fa:$VERSION .

            - name: Push image
              run: |
                  docker tag 2fa:$VERSION ghcr.io/hthanh12/2fa-express/2fa:$VERSION
                  docker tag 2fa:$VERSION ghcr.io/hthanh12/2fa-express/2fa:latest
                  docker push ghcr.io/hthanh12/2fa-express/2fa:$VERSION
                  docker push ghcr.io/hthanh12/2fa-express/2fa:latest
    Redeploy:
      name: Redeploy webhook call
      runs-on: ubuntu-18.04
      needs: [Deploy]
      steps:
        - name: Deploy docker container webhook
          uses: joelwmale/webhook-action@master
          env:
            WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
            data: "{ 'myField': 'myFieldValue'}"
